### ISSUE TITLE
"No screens found" İssue

### ISSUE THREAD

**Issue by furkanbr** [UnchartedBull/OctoDash#1039]
**What doesn't work?**
![20201004_001027_HDR](https://user-images.githubusercontent.com/53065065/95001831-632d8580-05d6-11eb-877d-8ce82537c3c8.jpg)
Octodash is not working , giving me this error.

**What did you already try?**
I installed octopi and octodash few times from 0 , check the drivers , raspi-config , and even tried with RPi zero but it didnt work.

**General Information:**
 - Hardware ; RPi 4 4GB Model , Waveshare 3.5inch RPi LCD (A), 480x320 
https://www.waveshare.com/3.5inch-RPi-LCD-A.htm
 - OS Info ; OctoPi Buster Lite 0.17
 - OctoDash Version ; Newest
 - OctoPrint Version ; Newest

**Additional context**
I added error that i get , i set my PRi to Autologin Console . When i turn on my Pi , octodash not showing even a second , just giving an error. Please help me to make it work. Thanks , have a good day.

**Comment by furkanbr** [comment]
Does anyone know how to solve ? im still getting this issue and didnt find how to solve.

**Comment by TheNeskik** [comment]
It doesn't look like an Octodash issue but an issue with xorg.
I can see here 2 problem : 
- No screen found -> Xorg configuration isn't pointing the right screen.
- Connection refused -> your pi user doesn't have the access to launch X server.

If you are on a fresh install of Octopi you need to install the touch driver as describe here first : 
https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(A)#Install_the_touch_driver

Secondly, you need to install Octodash with the script :)

If you already did the first point and you have the same issue, you will need to grant some permissions.

**Comment by furkanbr** [comment]
@TheNeskik Thanks for your answer !! i solved my problem with this link , if anyone having same problem it can help ;
https://raspberrypi.stackexchange.com/questions/100169/xorg-not-working-after-upgrading-to-buster/101085#101085?newreg=f7832854b4fe47a29a1597dafdb93ff6

**Comment by kekko7072** [comment]
I having the same error an I'm not able to solve it
This is the log file of the error. I tried everything also installing the desktop but nothing works. My LCD is correctly installed infact if I try desktop version of Raspbian it works perfectly the lcd and the touch scree. (THIS IS LINK TO WIKI OF LCD https://www.waveshare.com/wiki/5inch_HDMI_LCD)

PLS HELP ME!!


[    52.429] 
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
[    52.433] Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
[    52.434] Current Operating System: Linux octopi 5.10.11+ #1399 Thu Jan 28 12:02:28 GMT 2021 armv6l
[    52.434] Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
[    52.435] Build Date: 15 January 2021  02:03:57PM
[    52.435] xorg-server 2:1.20.4-1+rpt2+deb10u3 (https://www.debian.org/support) 
[    52.436] Current version of pixman: 0.36.0
[    52.436] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    52.436] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    52.438] (==) Log file: "/var/log/Xorg.0.log", Time: Fri Feb  5 22:22:03 2021
[    52.482] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    52.507] (==) No Layout section.  Using the first Screen section.
[    52.508] (==) No screen section available. Using defaults.
[    52.508] (**) |-->Screen "Default Screen Section" (0)
[    52.508] (**) |   |-->Monitor "<default monitor>"
[    52.544] (==) No device specified for screen "Default Screen Section".
	Using the first device section listed.
[    52.545] (**) |   |-->Device "Allwinner A10/A13 FBDEV"
[    52.545] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[    52.545] (==) Automatically adding devices
[    52.545] (==) Automatically enabling devices
[    52.545] (==) Automatically adding GPU devices
[    52.546] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    52.554] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    52.554] 	Entry deleted from font path.
[    52.555] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    52.555] 	Entry deleted from font path.
[    52.555] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    52.555] 	Entry deleted from font path.
[    52.556] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    52.556] 	Entry deleted from font path.
[    52.556] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    52.556] 	Entry deleted from font path.
[    52.556] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    52.557] 	Entry deleted from font path.
[    52.557] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[    52.557] (==) ModulePath set to "/usr/lib/xorg/modules"
[    52.557] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    52.557] (II) Loader magic: 0x1fdf80
[    52.558] (II) Module ABI versions:
[    52.558] 	X.Org ANSI C Emulation: 0.4
[    52.558] 	X.Org Video Driver: 24.0
[    52.558] 	X.Org XInput driver : 24.1
[    52.558] 	X.Org Server Extension : 10.0
[    52.602] (++) using VT number 7

[    52.603] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    52.604] (II) no primary bus or device found
[    52.605] (II) LoadModule: "glx"
[    52.614] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    52.774] (II) Module glx: vendor="X.Org Foundation"
[    52.775] 	compiled for 1.20.4, module version = 1.0.0
[    52.775] 	ABI class: X.Org Server Extension, version 10.0
[    52.775] (II) LoadModule: "fbturbo"
[    52.790] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so
[    52.800] (II) Module fbturbo: vendor="X.Org Foundation"
[    52.800] 	compiled for 1.20.3, module version = 0.5.1
[    52.800] 	Module class: X.Org Video Driver
[    52.801] 	ABI class: X.Org Video Driver, version 24.0
[    52.801] (II) FBTURBO: driver for framebuffer: fbturbo
[    52.823] (WW) Falling back to old probe method for fbturbo
[    52.823] (II) Loading sub module "fbdevhw"
[    52.823] (II) LoadModule: "fbdevhw"
[    52.824] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    52.866] (II) Module fbdevhw: vendor="X.Org Foundation"
[    52.874] 	compiled for 1.20.4, module version = 0.0.2
[    52.874] 	ABI class: X.Org Video Driver, version 24.0
[    52.875] (II) FBTURBO(0): using /dev/fb0
[    52.875] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[    52.876] (II) FBTURBO(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[    52.876] (==) FBTURBO(0): Depth 24, (==) framebuffer bpp 32
[    52.877] (==) FBTURBO(0): RGB weight 888
[    52.877] (==) FBTURBO(0): Default visual is TrueColor
[    52.877] (==) FBTURBO(0): Using gamma correction (1.0, 1.0, 1.0)
[    52.878] (II) FBTURBO(0): hardware: BCM2708 FB (video memory: 1500kB)
[    52.878] (DB) xf86MergeOutputClassOptions unsupported bus type 0
[    52.878] (**) FBTURBO(0): Option "fbdev" "/dev/fb0"
[    52.879] (**) FBTURBO(0): Option "SwapbuffersWait" "true"
[    52.920] (II) FBTURBO(0): processor: ARM1176
[    52.921] (II) FBTURBO(0): checking modes against framebuffer device...
[    52.921] (II) FBTURBO(0): checking modes against monitor...
[    52.921] (II) FBTURBO(0): Virtual size is 800x480 (pitch 800)
[    52.921] (**) FBTURBO(0):  Built-in mode "current"
[    52.922] (==) FBTURBO(0): DPI set to (96, 96)
[    52.922] (II) Loading sub module "fb"
[    52.922] (II) LoadModule: "fb"
[    52.923] (II) Loading /usr/lib/xorg/modules/libfb.so
[    52.980] (II) Module fb: vendor="X.Org Foundation"
[    52.980] 	compiled for 1.20.4, module version = 1.0.0
[    52.980] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    53.026] (II) FBTURBO(0): using backing store heuristics
[    53.251] (II) FBTURBO(0): can't load 'g2d_23' kernel module
[    53.252] (II) FBTURBO(0): failed to enable the use of sunxi display controller
[    53.252] (II) FBTURBO(0): No sunxi-g2d hardware detected (check /dev/disp and /dev/g2d)
[    53.253] (II) FBTURBO(0): G2D hardware acceleration can't be enabled
[    53.253] (II) FBTURBO(0): enabled fbdev copyarea acceleration
[    53.253] (==) FBTURBO(0): Backing store enabled
[    53.266] (==) FBTURBO(0): DPMS enabled
[    53.266] (II) FBTURBO(0): failed to enable hardware cursor
[    53.266] (II) FBTURBO(0): no 3D acceleration because the driver has been compiled without libUMP
[    53.267] (II) FBTURBO(0): if this is wrong and needs to be fixed, please check ./configure log
[    53.301] (II) Initializing extension Generic Event Extension
[    53.304] (II) Initializing extension SHAPE
[    53.312] (II) Initializing extension MIT-SHM
[    53.315] (II) Initializing extension XInputExtension
[    53.343] (II) Initializing extension XTEST
[    53.346] (II) Initializing extension BIG-REQUESTS
[    53.349] (II) Initializing extension SYNC
[    53.382] (II) Initializing extension XKEYBOARD
[    53.409] (II) Initializing extension XC-MISC
[    53.413] (II) Initializing extension SECURITY
[    53.421] (II) Initializing extension XFIXES
[    53.424] (II) Initializing extension RENDER
[    53.451] (II) Initializing extension RANDR
[    53.457] (II) Initializing extension COMPOSITE
[    53.493] (II) Initializing extension DAMAGE
[    53.496] (II) Initializing extension MIT-SCREEN-SAVER
[    53.498] (II) Initializing extension DOUBLE-BUFFER
[    53.523] (II) Initializing extension RECORD
[    53.532] (II) Initializing extension DPMS
[    53.535] (II) Initializing extension Present
[    53.538] (II) Initializing extension DRI3
[    53.538] (II) Initializing extension X-Resource
[    53.561] (II) Initializing extension XVideo
[    53.564] (II) Initializing extension XVideo-MotionCompensation
[    53.564] (II) Initializing extension SELinux
[    53.564] (II) SELinux: Disabled on system
[    53.565] (II) Initializing extension GLX
[    53.568] (II) AIGLX: Screen 0 is not DRI2 capable
[    58.066] (II) IGLX: Loaded and initialized swrast
[    58.066] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[    58.066] (II) Initializing extension XFree86-VidModeExtension
[    58.069] (II) Initializing extension XFree86-DGA
[    58.103] (II) Initializing extension XFree86-DRI
[    58.120] (II) Initializing extension DRI2
[    61.695] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/event5)
[    61.696] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[    61.696] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[    61.696] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[    61.696] (II) LoadModule: "evdev"
[    61.697] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[    61.758] (II) Module evdev: vendor="X.Org Foundation"
[    61.758] 	compiled for 1.20.3, module version = 2.10.6
[    61.759] 	Module class: X.Org XInput Driver
[    61.759] 	ABI class: X.Org XInput driver, version 24.1
[    61.759] (II) Using input driver 'evdev' for 'ADS7846 Touchscreen'
[    61.759] (**) ADS7846 Touchscreen: always reports core events
[    61.790] (**) evdev: ADS7846 Touchscreen: Device: "/dev/input/event5"
[    61.791] (--) evdev: ADS7846 Touchscreen: Vendor 0 Product 0
[    61.792] (--) evdev: ADS7846 Touchscreen: Found absolute axes
[    61.792] (--) evdev: ADS7846 Touchscreen: Found x and y absolute axes
[    61.792] (--) evdev: ADS7846 Touchscreen: Found absolute touchscreen
[    61.792] (**) Option "SwapAxes" "0"
[    61.793] (II) evdev: ADS7846 Touchscreen: Configuring as touchscreen
[    61.793] (**) Option "EmulateThirdButton" "1"
[    61.793] (**) Option "EmulateThirdButtonTimeout" "1000"
[    61.794] (**) Option "EmulateThirdButtonMoveThreshold" "300"
[    61.794] (**) evdev: ADS7846 Touchscreen: YAxisMapping: buttons 4 and 5
[    61.794] (**) evdev: ADS7846 Touchscreen: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    61.795] (**) Option "config_info" "udev:/sys/devices/platform/soc/20204000.spi/spi_master/spi0/spi0.1/input/input5/event5"
[    61.795] (II) XINPUT: Adding extended input device "ADS7846 Touchscreen" (type: TOUCHSCREEN, id 6)
[    61.796] (II) evdev: ADS7846 Touchscreen: initialized for absolute axes.
[    61.799] (**) ADS7846 Touchscreen: (accel) keeping acceleration scheme 1
[    61.832] (**) ADS7846 Touchscreen: (accel) acceleration profile 0
[    61.832] (**) ADS7846 Touchscreen: (accel) acceleration factor: 2.000
[    61.832] (**) ADS7846 Touchscreen: (accel) acceleration threshold: 4
[    61.876] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/mouse1)
[    61.877] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[    61.877] (II) No input driver specified, ignoring this device.
[    61.877] (II) This device may have been added with another device file.
[    61.984] (II) config/udev: Adding input device MOSART Semi. 2.4G Wireless Mouse (/dev/input/event0)
[    61.984] (**) MOSART Semi. 2.4G Wireless Mouse: Applying InputClass "evdev pointer catchall"
[    61.984] (**) MOSART Semi. 2.4G Wireless Mouse: Applying InputClass "evdev pointer catchall"
[    61.984] (II) Using input driver 'evdev' for 'MOSART Semi. 2.4G Wireless Mouse'
[    61.985] (**) MOSART Semi. 2.4G Wireless Mouse: always reports core events
[    61.985] (**) evdev: MOSART Semi. 2.4G Wireless Mouse: Device: "/dev/input/event0"
[    61.986] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Vendor 0x3938 Product 0x1031
[    61.986] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found 9 mouse buttons
[    61.986] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found scroll wheel(s)
[    61.986] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found relative axes
[    61.986] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found x and y relative axes
[    61.987] (II) evdev: MOSART Semi. 2.4G Wireless Mouse: Configuring as mouse
[    61.987] (II) evdev: MOSART Semi. 2.4G Wireless Mouse: Adding scrollwheel support
[    61.987] (**) evdev: MOSART Semi. 2.4G Wireless Mouse: YAxisMapping: buttons 4 and 5
[    61.988] (**) evdev: MOSART Semi. 2.4G Wireless Mouse: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    61.988] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:3938:1031.0001/input/input0/event0"
[    61.988] (II) XINPUT: Adding extended input device "MOSART Semi. 2.4G Wireless Mouse" (type: MOUSE, id 7)
[    61.989] (II) evdev: MOSART Semi. 2.4G Wireless Mouse: initialized for relative axes.
[    62.050] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) keeping acceleration scheme 1
[    62.050] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) acceleration profile 0
[    62.051] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) acceleration factor: 2.000
[    62.051] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) acceleration threshold: 4
[    62.106] (II) config/udev: Adding input device MOSART Semi. 2.4G Wireless Mouse (/dev/input/mouse0)
[    62.106] (II) No input driver specified, ignoring this device.
[    62.106] (II) This device may have been added with another device file.
[    62.226] (II) config/udev: Adding input device MOSART Semi. 2.4G Wireless Mouse (/dev/input/event1)
[    62.227] (II) No input driver specified, ignoring this device.
[    62.227] (II) This device may have been added with another device file.
[    62.307] (II) config/udev: Adding input device SEM USB Keyboard (/dev/input/event2)
[    62.307] (**) SEM USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    62.307] (**) SEM USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    62.308] (II) Using input driver 'evdev' for 'SEM USB Keyboard'
[    62.308] (**) SEM USB Keyboard: always reports core events
[    62.308] (**) evdev: SEM USB Keyboard: Device: "/dev/input/event2"
[    62.309] (--) evdev: SEM USB Keyboard: Vendor 0x1a2c Product 0x2124
[    62.309] (--) evdev: SEM USB Keyboard: Found keys
[    62.309] (II) evdev: SEM USB Keyboard: Configuring as keyboard
[    62.326] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/0003:1A2C:2124.0002/input/input2/event2"
[    62.326] (II) XINPUT: Adding extended input device "SEM USB Keyboard" (type: KEYBOARD, id 8)
[    62.326] (**) Option "xkb_rules" "evdev"
[    62.327] (**) Option "xkb_model" "pc105"
[    62.327] (**) Option "xkb_layout" "gb"
[    63.933] (II) config/udev: Adding input device SEM USB Keyboard Consumer Control (/dev/input/event3)
[    63.934] (**) SEM USB Keyboard Consumer Control: Applying InputClass "evdev keyboard catchall"
[    63.934] (**) SEM USB Keyboard Consumer Control: Applying InputClass "evdev keyboard catchall"
[    63.934] (II) Using input driver 'evdev' for 'SEM USB Keyboard Consumer Control'
[    63.935] (**) SEM USB Keyboard Consumer Control: always reports core events
[    63.935] (**) evdev: SEM USB Keyboard Consumer Control: Device: "/dev/input/event3"
[    63.935] (--) evdev: SEM USB Keyboard Consumer Control: Vendor 0x1a2c Product 0x2124
[    63.936] (--) evdev: SEM USB Keyboard Consumer Control: Found 1 mouse buttons
[    63.936] (--) evdev: SEM USB Keyboard Consumer Control: Found scroll wheel(s)
[    63.936] (--) evdev: SEM USB Keyboard Consumer Control: Found relative axes
[    63.936] (II) evdev: SEM USB Keyboard Consumer Control: Forcing relative x/y axes to exist.
[    63.937] (--) evdev: SEM USB Keyboard Consumer Control: Found absolute axes
[    63.937] (II) evdev: SEM USB Keyboard Consumer Control: Forcing absolute x/y axes to exist.
[    63.937] (--) evdev: SEM USB Keyboard Consumer Control: Found keys
[    63.937] (II) evdev: SEM USB Keyboard Consumer Control: Configuring as mouse
[    63.937] (II) evdev: SEM USB Keyboard Consumer Control: Configuring as keyboard
[    63.938] (II) evdev: SEM USB Keyboard Consumer Control: Adding scrollwheel support
[    63.938] (**) evdev: SEM USB Keyboard Consumer Control: YAxisMapping: buttons 4 and 5
[    63.938] (**) evdev: SEM USB Keyboard Consumer Control: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    63.939] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.4/1-1.4:1.1/0003:1A2C:2124.0003/input/input3/event3"
[    63.939] (II) XINPUT: Adding extended input device "SEM USB Keyboard Consumer Control" (type: KEYBOARD, id 9)
[    63.939] (**) Option "xkb_rules" "evdev"
[    63.970] (**) Option "xkb_model" "pc105"
[    63.970] (**) Option "xkb_layout" "gb"
[    63.973] (II) evdev: SEM USB Keyboard Consumer Control: initialized for relative axes.
[    63.973] (WW) evdev: SEM USB Keyboard Consumer Control: ignoring absolute axes.
[    63.976] (**) SEM USB Keyboard Consumer Control: (accel) keeping acceleration scheme 1
[    63.976] (**) SEM USB Keyboard Consumer Control: (accel) acceleration profile 0
[    63.977] (**) SEM USB Keyboard Consumer Control: (accel) acceleration factor: 2.000
[    63.977] (**) SEM USB Keyboard Consumer Control: (accel) acceleration threshold: 4
[    64.054] (II) config/udev: Adding input device SEM USB Keyboard System Control (/dev/input/event4)
[    64.055] (**) SEM USB Keyboard System Control: Applying InputClass "evdev keyboard catchall"
[    64.055] (**) SEM USB Keyboard System Control: Applying InputClass "evdev keyboard catchall"
[    64.055] (II) Using input driver 'evdev' for 'SEM USB Keyboard System Control'
[    64.056] (**) SEM USB Keyboard System Control: always reports core events
[    64.056] (**) evdev: SEM USB Keyboard System Control: Device: "/dev/input/event4"
[    64.056] (--) evdev: SEM USB Keyboard System Control: Vendor 0x1a2c Product 0x2124
[    64.057] (--) evdev: SEM USB Keyboard System Control: Found keys
[    64.057] (II) evdev: SEM USB Keyboard System Control: Configuring as keyboard
[    64.057] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.4/1-1.4:1.1/0003:1A2C:2124.0003/input/input4/event4"
[    64.058] (II) XINPUT: Adding extended input device "SEM USB Keyboard System Control" (type: KEYBOARD, id 10)
[    64.058] (**) Option "xkb_rules" "evdev"
[    64.058] (**) Option "xkb_model" "pc105"
[    64.058] (**) Option "xkb_layout" "gb"
