### ISSUE TITLE
tornado.access - WARNING - 409 GET /api/printer (127.0.0.1)

### ISSUE THREAD

**Issue by ahmed-elsaharti** [UnchartedBull/OctoDash#1086]
When my printer is powered off (using Tasmota+PSUControl) and Octodash is in 'sleep'/'standby' mode, the octoprint.log file fills with "tornado.access - WARNING - 409 GET /api/printer (127.0.0.1)" lines.

Tried to run octoprint in safe-mode to make sure its not a plugin that's causing this and it turned out to (probably) be octodash. This only occurs when the printer is powered off obviously since when its powered on Octodash is able to grab its status successfully

I've been looking around the issues and from what I understand there was a standby-mode improvement included in the latest release, not sure why this is happening in my case though. Any help would be appreciated ^_^

**Comment by UnchartedBull** [comment]
That is, unfortunately, how it is supposed currently. Angular is somehow not shutting down the services fully (didn't find a way to do so at least), thus they still are polling the API. All the request are properly handled on OctoDash side, so there isn't a performance decrease or possible overflow happening, it's just spamming the logs ...

There is however a fix for this planned already, which will be released with the next minor version after 2.1.0. This includes switching over to the OctoPrint JS library, which should handle this better and will also rely on a push concept, rather than a pull one. The library is already loaded and available in v2.1.0, I just need to replace all the API calls with the new library. Corresponding issue is #595.
