### ISSUE TITLE
Non critical error during update from 2.0 to 2.1

### ISSUE THREAD

**Issue by thegarbz** [UnchartedBull/OctoDash#1095]
During the update from 2.0 to 2.1 the Octodash.postinst script throws a command not found error:

"/var/lib/dpkg/info/octodash.postinst: line 10: update-desktop-database: command not found"

The update otherwise completed successfully to 2.1

Additionally a documentation error exists on the Wiki (It's too hard to make a pull request for a wiki change):
https://github.com/UnchartedBull/OctoDash/wiki/Installation#update-script
Under the installation page in the update script section the script name is incorrectly listed as 
"~/scripts/update.sh"
instead of:
"~/scripts/update-octodash"

The update page of the wiki is correct.

**Comment by UnchartedBull** [comment]
I think you were one of the early adopters, so you probably used an older version of the install script. You'll need to install `desktop-file-utils` in order to get rid of this error. The newer install scripts have this listed as a dependency :).

Good catch on the documentation! Somehow missed that I added this twice now. Removed the one from the Installation page and just linked back to the Update section.
