### ISSUE TITLE
Sleepmode after print finished - Will not wake up (I don't want it to sleep either)

### ISSUE THREAD

**Issue by KS-Husker** [UnchartedBull/OctoDash#1125]
With the latest update, my octodash goes to sleep and the screen goes black.
I can't get it to wake back up by touching it. 
I don't even want it to sleep, and don't have this selected in the settings on Octodash's menu. But it does it anyway.

The only way I can turn it on, is to power down the Pi and restart it. This is very annoying. 
Please fix this soon.

Also, I would rather go back to a previous version that was working better but I don't see a way to do this. That would be nice too, in case something really hoses up our printer with a new release. We are screwed.

**Comment by UnchartedBull** [comment]
I didn't change anything regarding sleep code with the last update, so this is really weird. Could you please double check if you haven't changed anything on OctoPrint that might cause this? Maybe OctoPrint is disconnecting from the printer after the job finished. 

Is it a black screen or a grayish one, Since there is no functionality to turn off the screen completely (it's always being turned on once you touch it by dpms).

You can always rollback. Just grab the Release URL from the releases tab, download with wget and then sudo dpkg -i the downloaded package. Please report if an older version fixes the issue.
