### ISSUE TITLE
[FR] Set connection timeout

### ISSUE THREAD

**Issue by lightmaster** [UnchartedBull/OctoDash#1550]
**Is your feature request related to a problem? Please describe.**
I'm using the Tasmota plugin to turn my printer on and off via a wifi outlet. Tasmota has the ability to automatically turn on when you "press" the connect button, including when trying to wake OctoDash.

When using the connect button on the website, Tasmota can initiate a second connection attempt after a set delay, used to account for the delay in the printer turning on.

When waking OctoDash, the printer turns on fine, but it seems like OctoDash gives up trying to connect too soon. The result is that I must tap the screen once to turn on the printer, wait for the connection attempts to timeout, then tap on the screen a second time to actually connect.

**Describe the solution you'd like**
I'd like a setting to adjust the number of connection attempts to be made and the timeout for those connection attempts.

**Link other projects**
If you want OctoDash to include other OctoPrint plugins or similar please link them here.

**Additional context**

**Comment by UnchartedBull** [comment]
Will be fixed by the linked PR. It doesn't add a configurable timeout, but rather OctoDash will automatically exit sleep once OctoPrint is connected. You're still being shown an error after 15s (20s if you use one of the integrated PSU controls), but it will switch over to main view any time OctoPrint connects.
