### ISSUE TITLE
Make temp sensor selectable via gui if possible

### ISSUE THREAD

**Issue by hawkeyexp** [UnchartedBull/OctoDash#1574]
I'm using ds18b20 (2 pieces) to track temp in print enaclosure and storage part of enclosure.
Only after searching the issues i found the solution how to setup (number of sensor 1/2 instead of sensor sn). A picklist of sensors to select from would be nice or to be more identical to encoslure plugin use the sensor sn 82-xxxxxxxx which would it make more clear.

**Comment by UnchartedBull** [comment]
Mhh this would be quite complex and will take a few hours to implement properly. The main problem is that this will be used usually once during setup and will then be forgotten about. Therefore I decided to focus on other features instead, sorry!

Changing to name also won't be possible since Enclosure is expecting the id via the API. It is documented here though: https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#enclosure-plugin-ambient-sensor
