### ISSUE TITLE
OctoDash can't connect to OctoPrint while Printer is disconnected (v2.1.2 nightly)

### ISSUE THREAD

**Issue by hawkeyexp** [UnchartedBull/OctoDash#1577]
System is now modified with psu control - relais swich controlled via gpio.

If sysem is powered off OctoDash can't connect to OctoPrint but webinterface of OctoPrint is accessible without any problems from pc.

Only after printer board is powered on and a connection is established to printer OctoDash can connect.

I think OctoDash should always connect but if no printer is connected it should reflect this state and allow the user to power on via psu or possible enable auto power on if psu plugin is used or allow retrigger a connect to printer from octoprint.

**Comment by UnchartedBull** [comment]
Will all be fixed with v3. v3 does connect to OctoPrint instance with no printer connected and you now have the option to open your custom actions from the sleep screen. Opening the normal UI while no printer is connected won't be possible and will probably never be supported since too much data is missing.
