### ISSUE TITLE
Add assistant for z-offset calibration while using probes like bltouch

### ISSUE THREAD

**Issue by hawkeyexp** [UnchartedBull/OctoDash#1880]
It would be nice to get an assistant/controlpanel for an easy setup of z-offset while using a proble like a bltouch.
I know it's not really often used but doing it manually with terminal is ugly and also marlin has included it in newer 2.x versions but not all printers can use this feautre by missing controls or customized displays from manufacturer.

requirements:

- inputfield for x/y offset of probe and possible read of current values from the firmware
- buttons to move to testposition (one to place nozzle / one to place probe at same postion as nozzle calculated by offsets)
- enable heating for bed and nozzle with dest-temp
- controls for pin out and pin in / if possible receiving trigger signal and blocking of z down
- controls for z up and down with different steppings like 1mm / 0.2 / 0.1 / 0.02
- view of current z position
- accept button which calculates offset and store firmware
- optional: a cam window ( 1/4 of screen for example) for users with nozzle cams :-)

I think it woukld be a great feature for octodash!

**Comment by UnchartedBull** [comment]
This does seem like a very advanced feature. It'll probably take a good amount fo work to get this working and since you already mentioned it: it won't be used often. I do think Z Offset is a needed feature to finally fully ditch the stock screens. That will be tracked in #1092 and hopefully will be included in one of the next features.

For the other features: They are probably out of spec for OctoDash. Most of the functionality should be able to be handled by Custom Actions though. I'm not going to work on this and closing this here now. Sorry! I'll be happy to accept a PR for this feature, if you feel up to the task :)
