### ISSUE TITLE
NOX theme V0.2.2 out of range for filament change screen

### ISSUE THREAD

**Issue by Jack77777777** [UnchartedBull/OctoDash#1892]
@noxhirsch can you adjust this ? See attached picture.
![IMG_4090](https://user-images.githubusercontent.com/64719909/120441537-f34de580-c384-11eb-8503-d31555cd99d5.jpg)

**Comment by noxhirsch** [comment]
I'll try to fix it later today or tomorrow 👍

**Comment by noxhirsch** [comment]
After some trial & error without succes, I checked if this also happens without the NOX theme - and it does indeed.
The way I see it, two changes need to be made in OctoDash, but I have no time to setup a dev instance at the moment, to try that out. In theory, this should fix the problem:

Either the second `<span>` must be integrated into the first one - or both spans need a wrapper div/span:
https://github.com/UnchartedBull/OctoDash/blob/2ed9b86473a6451150a2fe0004a6962d1929061d/src/app/filament/change-filament/change-filament.component.html#L17-L20

I'd prefer the first solution, if it doesn't cause any problems. But if a wrapper around both spans is used, these styles should be moved to the wrapper:
https://github.com/UnchartedBull/OctoDash/blob/2ed9b86473a6451150a2fe0004a6962d1929061d/src/app/filament/change-filament/change-filament.component.scss#L18-L23
Then either the wrapper or the two spans need to have `display:inline;` instead of `display:block;` (I'm not sure if both works, I would have to try that out)

**Comment by UnchartedBull** [comment]
Oh this must've happened with the i18n integration. I'm going to fix this. Thanks for reporting / providing a fix!

**Comment by Jack77777777** [comment]
Is this already fixed ? If yes, what do i have to do ?

**Comment by UnchartedBull** [comment]
Not fixed yet. Will be released with the next version.
