### ISSUE TITLE
Needs a simple install for a Noob like me :)

### ISSUE THREAD

**Issue by nedla1969** [UnchartedBull/OctoDash#266]
Best looking TFT Ui, how simple is it to install..

**Comment by UnchartedBull** [comment]
Just execute this line of code on the pi (either via ssh or via an attached keyboard):

```
wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/install.sh | bash -s -- --ptg
```

*This will install additional OctoPrint plugins, listed here: https://github.com/UnchartedBull/OctoDash/wiki/Installation#automatic-installation*

**Comment by UnchartedBull** [comment]
This will also install  a new Desktop and configure automatic start on boot. Do you currently have a Desktop running on your system?

**Comment by UnchartedBull** [comment]
yes. You may want to uninstall octoprint-tft first to avoid any weird behavior ...

**Comment by UnchartedBull** [comment]
If you managed to install OctoDash please close this issue :)

**Comment by evannadeau** [comment]
I just went through the setup on a fresh 0.17.0 deployment of OctoPi, and the automated version did not work.  I had to configure the console autologin, as well as the very last step in the manual config, sudo chmod ug+s /usr/lib/xorg/Xorg

**Comment by UnchartedBull** [comment]
Thanks for the info. Those two steps will be always manual effort. I won't automate the automatic login, because that can be a huge security risk and I want the users do note, that they open up the system to anyone that can plugin a power chord.

The chmod thing only occurs on some installations, therefore it is not in the main script. I'll make sure, that it is more obvious in the wiki which steps needed to be done manually.

**Comment by evannadeau** [comment]
Fantastic, thanks.
