### ISSUE TITLE
USB support + recover print after power loss

### ISSUE THREAD

**Issue by Stijn-Verhelst** [UnchartedBull/OctoDash#508]
Since I don't have a Raspberry Pi yet, I wasn't able to test OctoDash , but I may have some features that could be helpful for everyone:

1. Since most of the Raspberry Pi family have a USB port (except for the Zero ...), it could be nice if we could print from a USB-drive. This way, we can choose which method we pick for printing (via the octoprint webpage or USB). 

2. Because powerlosses aren't predictable, we never know when they happen. It could happen when we are running a 20+ hour print. It would be helpful if there was a "power loss recovery" screen, so we have the option to further print the model. (Marlin has this option on their screen, CMIIW).

As I already said, I don't have a Pi to test the already implemented features of OctoDash, so sorry if one of these are already implemented.

Kind regards
Stijn Verhelst

**Comment by UnchartedBull** [comment]
Hi, the two points you're making here are definitely valid and good points, they're not within the scope of OctoDash though. Since OctoDash only is a frontend for the OctoPrint API these two features should be handled by OctoPrint instead of OctoDash. Maybe search and open an issue in their repo :).
