### ISSUE TITLE
OctoDash on my master controller can't connect to my printer

### ISSUE THREAD

**Issue by richgain** [UnchartedBull/OctoDash#596]
I have installed OctoDash on my master controller but I can't connect to my printer(s).
I have three different 3D printers in my workshop. Each one has its own RPi running Octoprint.
I have a fourth Raspberry Pi with a 7" touch screen that use to control all the others.
I have installed OctoDash on this machine but I have been unable to connect to the printers.

I have managed to get OctoDash to run from the command line but when I provide the IP address and API key of a printer on the network, the config tool just reports a response failure.
I accidentally installed OctoDash with the auto-start option. The second image shows how the Raspbian desktop boots up now. I simply type "octodash" at the command prompt to get to the configuration wizard.

Raspberry Pi 3B in printers and controller
 - OctoPi in the printer / Raspbian full desktop in the controller
 - OctoDash Version v1.4.1
 - OctoPrint Version v1.4.0

Not sure if 5000 is the wrong port to use if Octoprint is running on another Pi or if something else is wrong. 

![IMG_3011](https://user-images.githubusercontent.com/1440566/80283423-52b3dd80-870f-11ea-98c7-4a2a5363a722.JPG)
![IMG_3009](https://user-images.githubusercontent.com/1440566/80283426-57789180-870f-11ea-89d2-b475fb0628ee.JPG)

**Comment by UnchartedBull** [comment]
Regarding the startup issue: just remove the line `ratpoison&` from your `~/.xinitrc`. Otherwise Raspbian will try to create to desktops, which will not work.

Regarding the Setup error: Error Code 0 indicates that the host:Port can‘t be reached. Please make sure that your firewall allows traffic on port 5000 and that you have the proxy correctly setup for port 5000. If you run OctoPi you need to chose port 80 instead I think, if you want to access the API from another machine. So try with Port 80 first and then check your Firewall :)

**Comment by richgain** [comment]
Perfect! Thank you very much.
