### ISSUE TITLE
Possible issue when updating?

### ISSUE THREAD

**Issue by ruralaccent** [UnchartedBull/OctoDash#652]
I just ran the update script via Putty and received the following warning:

![OctoDash Update Putty Error](https://user-images.githubusercontent.com/51720842/82154205-2e59a580-9864-11ea-84e2-100a2799db69.PNG)

The update seems to have worked ok and Octodash seems to be running ok, but as I've not run the update script before, I don't know if this is to be expected?

I am running a Pi4 (4GB) with the latest Octoprint version.

**Comment by UnchartedBull** [comment]
From what I can see the script somehow didn't get the current release properly. Maybe try again to see if this works now, otherwise just do:

`wget -O octodash.deb https://github.com/UnchartedBull/OctoDash/releases/download/v1.5.0/octodash_1.5.0_armv7l.deb -q` and then `sudo dpkg -i octodash.deb`. After that you can delete octodash.deb with `rm octodash.deb`

**Comment by ruralaccent** [comment]
Sorted. thank you!
