### ISSUE TITLE
Can the close button overlay in the internet browser stay while navigating

### ISSUE THREAD

**Issue by graphiste** [UnchartedBull/OctoDash#713]
Hi, I use the internet page custom action to open Octprint on the enclosure plugin tab. It works great while navigating between the main Octoprint tabs.
If I click thugh on a link that is not a tab, the new page loads, but the close button desapears and I can not return to octodash screen.
Is it possible to aways have the close button overlay while navigating internet in kiosk mode?

**Comment by UnchartedBull** [comment]
The close button should always stay, so this is a bug, will try to fix it for the next release.

**Comment by UnchartedBull** [comment]
The linked PR will fix that issue. The problem is, that there is no way to display a website, if the link wants to open a new window. With the new implementation it will just ignore that link. While this means, that the close button will always be visible, it also means that you probably can't open the website that caused the issue anymore.

Can you maybe update the website to use targer="__self" instead of blank or similar?

**Comment by graphiste** [comment]
Thank you very much for solving this issue.
