### ISSUE TITLE
Filament Swap - Keeps advancing filament after selecting OK

### ISSUE THREAD

**Issue by KS-Husker** [UnchartedBull/OctoDash#968]
When doing the filament swap, prior to printing. (Still don't see a very good way mid-printing)
I set the distance to add filament as a long distance so it keeps going. Once I touched the OK button I thought it would stop advancing filament but it just kept going the distance I had set it to. 

Can you make it send a stop command once you click the OK button so it stops advancing filament and goes back to the home screen? Otherwise it works beautifully.

**Comment by UnchartedBull** [comment]
You need to enable EMERGENCY_STOP for that (although it is not recommended, since it invalidates the stepper positions). Only way to stop a movement mit print though. I would suggest setting the length to approximately the right size and then use the purge screen to advance more filament in 10mm steps if needed. More info: https://marlinfw.org/docs/gcode/M410.html
