### ISSUE TITLE
Custom splash screen and logos

### ISSUE THREAD

**Issue by Dario-Ciceri** [UnchartedBull/OctoDash#980]
Please add a method to use custom splash screen on boot and use custom logos and home title. For example instead of "OctoDash" as home page title -> "Hypercube Evolution + logo image"

**Comment by UnchartedBull** [comment]
Not really within the scope of the project for now. Replacing the splash screen dynamically isn't possible at all, because Angular hasn't loaded all the libraries yet, so you need to have a static website there. I don't have the ressources to work on this. Feel free to create a Fork with your custom name and logo though :)
